version: "2"

#######################################
# project_name: aulinks-test-task #
#######################################

services:
  php:
    build:
      context: docker/php
    image: aulinks-php:7
    container_name: aulinks-php
    depends_on:
      - mysql
    environment:
      PHP_IDE_CONFIG: serverName=aulinks.local
      APP_LOG_DIR: /var/log/aulinks
      APP_CACHE_DIR: /var/cache
      APP_SPOOL_DIR: /var/cache/spool
      JWT_SECRET: secret_password
      #To use smtp a needed to change swiftmailer transport in src/Command/MailerSpoolCommand.php
      MAIL_SMTP_HOST: smtp.example.org
      MAIL_SMTP_PORT: 25
      MAIL_SMTP_SECURITY: ""
      MAIL_SMTP_USERNAME: enter_your_username
      MAIL_SMTP_SECURITY: enter_your_password
    volumes:
      - .:${PWD}
    working_dir: ${PWD}

  nginx:
    image: nginx:1
    container_name: aulinks-nginx
    depends_on:
      - php
    volumes:
      - .:${PWD}
      - ./docker/nginx/default.tpl:/etc/nginx/conf.d/default.tpl
    networks:
      default:
        aliases:
          - aulinks.local
    environment:
      NGINX_AULINKS_PROJECT_PATH: ${PWD}
    ports:
      - 80:80
    command: /bin/bash -c "envsubst '$${NGINX_AULINKS_PROJECT_PATH}' < /etc/nginx/conf.d/default.tpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mysql:
    image: mariadb
    container_name: aulinks-mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: aulinks_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: aulinks
      MYSQL_PASSWORD: aulinks

volumes:
  mysql:
    driver: local

networks:
  default:
    external:
      name: aulinks